### PR TITLE
import of iris_drs version 2021.01.29

### PR DESCRIPTION
**Pull request by zonca**
Following #26, I have used the software in https://github.com/oirlab/iris_metadata to regenerate `subscribe-model.conf` from the master sheet on Google Docs.

The issue is that formatting using `pyhocon` is different to what is used in this repository (e.g. quoting, indentation). What do you recommend? Thanks!

### CODE REVIEW

**Comment by zonca** [comment]
I simply used:

```python
generated_config = ConfigFactory.from_dict(conf)
from pyhocon.converter import HOCONConverter
with open("generated-subscribe-model.conf", "w") as f:
    f.write(HOCONConverter().to_hocon(generated_config))
```

**Review by edwardchapin — COMMENTED** [review]
I don't mind about the format change. Every file is formatted differently at the moment. Since I imagine you will continue to manage this using the script, it shouldn't change much in the future.

Ideally there would be two separate commits: one with any content changes, and another with the format change. However, that's probably not practical. Perhaps you could summarize in a comment here how the content changes with this PR? I'm working on some ICDs that may depend on this, so I'd like to know what's new.

**Comment by zonca** [comment]
thanks @edwardchapin, actually there is no change in content, I started from the old file, went through Google Sheets and back to this new file.
In the process the order changed when I did join with the rest of the metadata, but nothing else.

**Comment by edwardchapin** [comment]
> thanks @edwardchapin, actually there is no change in content, I started from the old file, went through Google Sheets and back to this new file.
> In the process the order changed when I did join with the rest of the metadata, but nothing else.

Great, looks good to me... feel free to go ahead and merge.

**Pull request merged**
