### PR TITLE
Initial add of IRIS model files from IRIS fork

### PR DESCRIPTION
**Pull request by jasonweiss**
Not complete, but enough to get started...

### CODE REVIEW

**Comment by chrisaj5** [comment]
Not finding anywhere else to request this... so could I please be added as a collaborator for this repository?

**Comment by scroberts** [comment]
Copying from e-mail discussion that should have gone here:

**Scott Wrote**:
I have one question for either you or Kim….  I noticed that there is nothing printed in the API for items that have a component-model.conf file but no publish-model.conf file.  For example “1-wire-hcd”.  Is this what’s expected from the database?  I would have thought that we should still print the information in the component-model file even if there were no current publish/subscribes for that entry.

Other than this I’ve had a read through the model files and am okay with pulling these into the repository.  

**Jason replied:** i should have made it clear that not all of the publish, subscribe, and command models files exist yet for our subsystem.  i was just pushing to you what we do have.  it is probable that all components will have at least one of those eventually.

**Comment by scroberts** [comment]
Okay, I think that’s fine for this initial release.  That still leaves the question of whether the API should print the content of component-model.conf files even if there is no publish/subscribe information.

**Comment by jasonweiss** [comment]
Kim should be added as a collaborator, if he isn't already.  Is he getting notifications about this thread?

**Comment by jasonweiss** [comment]
I agree with you scott.  seems like it should.

**Comment by abrighton** [comment]
Hi Scott,

I added an icd issue (https://github.com/tmtsoftware/icd/issues/30) and 
I'll check into this later.

## 

Allan

**Comment by scroberts** [comment]
Jason, Kim and I have been discussing the work-flow for model file updates.  Soon you'll be able to push directly to the submodule yourself.  The approval / release process will happen at the step of updating the commit to the Root Repository (done at the time of a formal release of an API).  This will allow you and other teams to update their submodules and cross-check ICDs before making a request to formally publish the ICD.

**Pull request merged**
